=== Jisu-Woniu/Blog/links-info-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"title": "JSON Schema for post-info.json",

	"type": "array",
	"items": {
		"type": "object",
		"required": [
			"name",
			"description",
			"link",
			"icon"
		],
		"properties": {
			"name": {
				"type": "string"
			},
			"description": {
				"type": "string"
			},
			"link": {
				"type": "string",
				"format": "uri"
			},
			"icon": {
				"type": "string",
				"format": "uri"
			}
		}
	}
}

=== Jisu-Woniu/Blog/wwwroot/links-info.json
[
    {
        "name": "Cxy621",
        "description": "后端的神，您什么时候当主席？",
        "link": "https://cxy621.top/",
        "icon": "https://cxy621.top/medias/avatar.jpg"
    },
    {
        "name": "Moroshima",
        "description": "别摸鱼了，快起来做锅",
        "link": "https://kuroshima.top/",
        "icon": "https://kuroshima.top/wp-content/uploads/2022/02/Moroshima.png"
    },
    {
        "name": "Maxtune Lee",
        "description": "学弟，菜菜，带带",
        "link": "https://mxte.cc/",
        "icon": "https://mxte.cc/wp-content/uploads/2020/10/cropped-60775796.png"
    },
    {
        "name": "風楪fy",
        "description": "可拷大哥哥，嘉心糖头子",
        "link": "http://fengye404.top/",
        "icon": "https://q.qlogo.cn/headimg_dl?dst_uin=1129126684&spec=640"
    }
]
